// AUTO-GENERATED by scripts/build-captions.mjs — do not edit by hand.
window.__captions = {
  "01-problem": [
    {
      "text": "Your AI agents and your apps",
      "start": 0.05,
      "end": 1.49
    },
    {
      "text": "Generate real data now.",
      "start": 1.56,
      "end": 3.32
    },
    {
      "text": "Files, artifacts, memory, but where does",
      "start": 3.38,
      "end": 5.53
    },
    {
      "text": "It actually live on someone's server,",
      "start": 5.53,
      "end": 7.2
    },
    {
      "text": "Behind someone's login, deletable by someone",
      "start": 7.25,
      "end": 9.56
    },
    {
      "text": "Else? WalDrive is a desktop drive",
      "start": 9.64,
      "end": 11.7
    },
    {
      "text": "For Walrus, your files stored on",
      "start": 11.77,
      "end": 13.55
    },
    {
      "text": "A decentralized network owned by you",
      "start": 13.6,
      "end": 15.58
    },
    {
      "text": "And verifiable by anyone.",
      "start": 15.69,
      "end": 17.26
    }
  ],
  "02-welcome": [
    {
      "text": "Setup is one click.",
      "start": 0.14,
      "end": 1.54
    },
    {
      "text": "WalDrive generates a key on your",
      "start": 1.54,
      "end": 3.04
    },
    {
      "text": "Machine, it signs everything in-process.",
      "start": 3.04,
      "end": 5.6
    },
    {
      "text": "No extension, no pop-ups.",
      "start": 5.75,
      "end": 7.84
    }
  ],
  "03-faucet": [
    {
      "text": "A fresh wallet needs gas, WalDrive's",
      "start": 0.04,
      "end": 2.58
    },
    {
      "text": "Faucet lands it in one click",
      "start": 2.67,
      "end": 3.97
    },
    {
      "text": "Instant on devnet captcha-free.",
      "start": 4.24,
      "end": 6.1
    }
  ],
  "04-upload": [
    {
      "text": "Now drag files in — plural.",
      "start": 0.06,
      "end": 1.8
    },
    {
      "text": "A photo, notes, a log.",
      "start": 1.82,
      "end": 3.32
    },
    {
      "text": "Each one streams to the Walrus",
      "start": 3.41,
      "end": 4.71
    },
    {
      "text": "Network, lands as an object on",
      "start": 4.71,
      "end": 6.25
    },
    {
      "text": "Sui, and appears the moment it",
      "start": 6.25,
      "end": 7.73
    },
    {
      "text": "Confirms. No backend anywhere.",
      "start": 7.73,
      "end": 10.64
    }
  ],
  "05-verify": [
    {
      "text": "Notes render straight from the aggregator",
      "start": 0.04,
      "end": 2
    },
    {
      "text": "With the real expiry epoch on",
      "start": 2,
      "end": 3.83
    },
    {
      "text": "Display. Hit Verify the bytes are",
      "start": 3.83,
      "end": 5.99
    },
    {
      "text": "Re-fetched and hashed on screen.",
      "start": 5.99,
      "end": 7.66
    },
    {
      "text": "Don't trust us.",
      "start": 7.76,
      "end": 8.71
    },
    {
      "text": "Check.",
      "start": 8.76,
      "end": 9.14
    }
  ],
  "06-organize": [
    {
      "text": "Organize like a real drive.",
      "start": 0.04,
      "end": 2
    },
    {
      "text": "Folders, tags, search.",
      "start": 2.04,
      "end": 3.4
    },
    {
      "text": "Every change is a transaction you",
      "start": 3.44,
      "end": 5.03
    },
    {
      "text": "Own, and the sidebar reads straight",
      "start": 5.03,
      "end": 6.88
    },
    {
      "text": "From chain.",
      "start": 6.88,
      "end": 7.6
    }
  ],
  "07-versions": [
    {
      "text": "Files have history here.",
      "start": 0.11,
      "end": 1.4
    },
    {
      "text": "Ship a new revision.",
      "start": 1.51,
      "end": 2.4
    },
    {
      "text": "The old one never leaves the",
      "start": 2.51,
      "end": 3.99
    },
    {
      "text": "Chain. Open History.",
      "start": 4.06,
      "end": 5.52
    },
    {
      "text": "Hit Restore.",
      "start": 5.63,
      "end": 6.4
    },
    {
      "text": "One transaction.",
      "start": 6.51,
      "end": 7.36
    },
    {
      "text": "No re-upload, and you're back.",
      "start": 7.47,
      "end": 10
    }
  ],
  "08-storage": [
    {
      "text": "These are your storage receipts, actual",
      "start": 0.08,
      "end": 1.94
    },
    {
      "text": "Walrus Blob objects in your wallet.",
      "start": 1.94,
      "end": 4.24
    },
    {
      "text": "Extend one's life right from Settings.",
      "start": 4.32,
      "end": 6.34
    },
    {
      "text": "Renew or delete. Your call, your",
      "start": 6.42,
      "end": 8.23
    },
    {
      "text": "Keys.",
      "start": 8.23,
      "end": 8.74
    }
  ],
  "09-accounts": [
    {
      "text": "Because everything lives on chain, your",
      "start": 0.05,
      "end": 2.07
    },
    {
      "text": "Drive follows your key.",
      "start": 2.15,
      "end": 3.68
    },
    {
      "text": "Import it on any machine and",
      "start": 3.73,
      "end": 5.21
    },
    {
      "text": "The whole thing comes back.",
      "start": 5.21,
      "end": 6.67
    }
  ],
  "10-mcp": [
    {
      "text": "And it's not just for humans.",
      "start": 0.05,
      "end": 1.8
    },
    {
      "text": "WalDrive ships an MCP server, your",
      "start": 1.85,
      "end": 4.19
    },
    {
      "text": "Agents and scripts operate the same",
      "start": 4.31,
      "end": 6.1
    },
    {
      "text": "Drive with the same keys.",
      "start": 6.15,
      "end": 7.72
    }
  ],
  "11-conclusion": [
    {
      "text": "WalDrive, the file management and verifiable",
      "start": 0.04,
      "end": 2.51
    },
    {
      "text": "Data console for everything your agent",
      "start": 2.51,
      "end": 5.04
    },
    {
      "text": "Store on Walrus.",
      "start": 5.04,
      "end": 6.04
    },
    {
      "text": "Real bytes, real ownership verifiable by",
      "start": 6.08,
      "end": 8.7
    },
    {
      "text": "Anyone. Built for Sui Overflow 2026",
      "start": 8.7,
      "end": 11.74
    },
    {
      "text": "Walrus track.",
      "start": 11.74,
      "end": 12.82
    }
  ]
};
